name: NeoSpecies
version: 1.0
description: LMAA
author: Neocrafter
website: www.neocrafter.de
main: de.neocrafter.neospecies.NeoSpecies
#softdepend: []
commands:
    species:
        description: lmaa
permissions:
    admin:
        assign:
            description: lmaa
